import { type RouteConfig, index, layout, route } from '@react-router/dev/routes';

export default [
  route('login', 'routes/login.tsx'),
  route('sign-up', 'routes/sign-up.tsx'),
  route('mfa/enroll', 'routes/mfa/enroll.tsx'),
  layout('routes/layout.tsx', [
    index('routes/dashboard.tsx'),
    route('deliveries', 'routes/deliveries.tsx'),
    route('drivers', 'routes/drivers.tsx'),
    route('drivers/:driverId', 'routes/drivers.$driverId.tsx'),
    route('carriers', 'routes/carriers.tsx'),
    route('carriers/:carrierId', 'routes/carriers.$carrierId.tsx'),
    route('carriers/applications', 'routes/carriers.applications.tsx'),
    route('carriers/applications/:applicationId', 'routes/carriers.applications.$applicationId.tsx'),
    route('users', 'routes/users.tsx'),
    route('users/:userId', 'routes/users.$userId.tsx'),
    route('customers', 'routes/customers.tsx'),
    route('customers/:customerId', 'routes/customers.$customerId.tsx'),
    route('analytics', 'routes/analytics.tsx'),
    route('settings', 'routes/settings.tsx'),
    route('settings/alerts', 'routes/settings/alerts.tsx'),
    route('settings/fee-settings', 'routes/settings/fee-settings.tsx'),
    route('settings/profile', 'routes/settings/profile.tsx'),
    route('settings/name-changes', 'routes/settings/name-changes.tsx'),
    route('notifications', 'routes/notifications.tsx'),
    route('notifications/broadcast', 'routes/notifications.broadcast.tsx'),
    route('disputes', 'routes/disputes.tsx'),
    route('verifications', 'routes/verifications.tsx'),
    route('payouts', 'routes/payouts.tsx'),
    route('waitlist', 'routes/waitlist.tsx'),
    route('coverage/zones', 'routes/coverage/zones.tsx'),
  ]),
] satisfies RouteConfig;
